name: todoapp
description: wow

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  # state management
  flutter_bloc: ^3.2.0
  shared_preferences: ^0.5.6+3
  # dart support
  equatable: ^1.1.1
  dartz: ^0.8.9
  data_connection_checker: ^0.3.4
  # service locator
  get_it: ^4.0.1
  # firebase
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  # flare
  flare_flutter: ^2.0.1
  # UI
  cupertino_icons: ^0.1.3
  form_field_validator: ^1.0.1
  flutter_datetime_picker: ^1.3.5
  flutter_local_notifications: ^1.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1


flutter:

  uses-material-design: true

  assets:
    - assets/fonts/Raleway-Regular.ttf
    - assets/fonts/Abel-Regular.ttf
    - assets/fonts/BalooChettan2-Regular.ttf
    - assets/fonts/Handlee-Regular.ttf
    - assets/fonts/Montserrat-Regular.ttf
    - assets/fonts/NanumPenScript-Regular.ttf
    - assets/fonts/OpenSansCondensed-Light.ttf
    - assets/fonts/Sen-Regular.ttf
    - assets/fonts/TitanOne-Regular.ttf
    - assets/animations/Logo.flr
    - assets/animations/Intro1.flr
    - assets/animations/Intro2.flr
    - assets/animations/Intro3.flr


  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: Abel
      fonts:
          - asset: assets/fonts/Abel-Regular.ttf
    - family: BalooChettan2
      fonts:
          - asset: assets/fonts/BalooChettan2-Regular.ttf
    - family: Handlee
      fonts:
          - asset: assets/fonts/Handlee-Regular.ttf
    - family: Montserrat
      fonts:
          - asset: assets/fonts/Montserrat-Regular.ttf
    - family: NanumPenScript
      fonts:
          - asset: assets/fonts/NanumPenScript-Regular.ttf
    - family: OpenSansCondensed
      fonts:
          - asset: assets/fonts/OpenSansCondensed-Light.ttf
    - family: Sen
      fonts:
          - asset: assets/fonts/Sen-Regular.ttf
    - family: TitanOne
      fonts:
          - asset: assets/fonts/TitanOne-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
